version: 2

jobs:
  tests:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/rcmachado/changelog
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - run: mkdir -p $TEST_RESULTS
      - run: go get -v -t -d ./...
      - run: go get -u github.com/jstemmer/go-junit-report
      - run:
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -v ./... | tee ${TEST_RESULTS}/go-test.out
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/rcmachado/changelog
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run:
          command: |
            curl --location -o goreleaser.tar.gz https://github.com/goreleaser/goreleaser/releases/download/v0.77.2/goreleaser_Linux_x86_64.tar.gz
            tar xzf goreleaser.tar.gz goreleaser
            ./goreleaser --snapshot
      - store_artifacts:
          path: dist
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - tests
      - release
