version: 2

jobs:
  tests:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rcmachado/changelog
    environment:
      TEST_RESULTS: /tmp/test-results
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.sum" }}
      - run: mkdir -p $TEST_RESULTS
      - run: make install
      - run:
          command: |
            trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
            go test -cover -race -coverprofile=${TEST_RESULTS}/coverage.out -v ./... | tee ${TEST_RESULTS}/go-test.out
      - run:
          command: |
            [ ! -z "${COVERALLS_TOKEN}" ] && goveralls -coverprofile=${TEST_RESULTS}/coverage.out -service=circle-ci -repotoken="${COVERALLS_TOKEN}"
      - run: make lint
      - save_cache:
          key: v1-pkg-cache-{{ checksum "go.sum" }}
          paths:
            - /go/pkg
      - store_artifacts:
          path: /tmp/test-results
          destination: raw-test-output
      - store_test_results:
          path: /tmp/test-results

  release:
    docker:
      - image: circleci/golang:1.13
    working_directory: /go/src/github.com/rcmachado/changelog
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-pkg-cache-{{ checksum "go.sum" }}
      - run: go get -v -t -d ./...
      - run: go build -o /tmp/changelog-current main.go
      - run:
          command: |
            [[ "$CIRCLE_TAG" == "" ]] && OPTS="--snapshot"
            curl -o /tmp/goreleaser -sL https://git.io/goreleaser
            bash /tmp/goreleaser $OPTS --release-notes <(/tmp/changelog-current -f /go/src/github.com/rcmachado/changelog/CHANGELOG.md show ${CIRCLE_TAG:-unreleased})
      - store_artifacts:
          path: dist
          destination: builds

workflows:
  version: 2
  build:
    jobs:
      - tests:
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
      - release:
          requires:
            - tests
          filters:
            tags:
              only: /^\d+\.\d+\.\d+$/
